//------------
//System Values
//------------
var STAGE_WIDTH = 800,
	STAGE_HEIGHT = 600,
	TIME_PER_FRAME = 33, //this equates to 30 fps
	GAME_FONTS = "bold 20px sans-serif";
	
//Game States
var GAMESTATE_PRELOAD = "preloading",
	GAMESTATE_MENU = "menu",
	GAMESTATE_GAMEPLAY = "gameplay",
	GAMESTATE_RESULTS = "results";
	
//------------
//Preloading
//------------
var TEXT_PRELOADING = "Loading ...",
	TEXT_PRELOADING_X = 325,
	TEXT_PRELOADING_Y = 300;
	
//-----------------
//ART ASSETS PATHS
//-----------------
var PATH_FROGGER = "img/frogger.png",
	FROG_MOTION_OFFSET_X = 50,
	HOME_OFFSET_X = 100,
	HOME_OCCUPIED_OFFSET_X = 150,
	CAR_OFFSET_X = 200,
	LOG_OFFSET_X = 300;
	
//-----------------
//MENU CONSTANTS
//-----------------
var MENU_START_BUTTON_X = 325,
	MENU_START_BUTTON_Y = 300,
	MENU_START_BUTTON_WIDTH = 150,
	MENU_START_BUTTON_HEIGHT = 20,
	TEXT_START_BUTTON = "Click to START";

//-----------------
//RESULTS CONSTANTS
//-----------------
var RESULTS_WON = "won",
	RESULTS_LOST = "lost",
	RESULTS_RESTART_BUTTON_X = 325,
	RESULTS_RESTART_BUTTON_Y = 300,
	RESULTS_RESTART_BUTTON_WIDTH = 175,
	RESULTS_RESTART_BUTTON_HEIGHT = 20,
	TEXT_RESTART_BUTTON = "Click to RESTART",
	TEXT_WON_X = 360,
	TEXT_WON_Y = 200,
	TEXT_WON = "You won!",
	TEXT_LOST_X = 360,
	TEXT_LOST_Y = 200,
	TEXT_LOST = "You lost!";

//-----------------
//GAME CONSTANTS
//-----------------
var	INIT_LIFE = 3,
	MAX_TIMER = 99
	FROG_START_X = 400,
	FROG_START_Y = 550,
	FROG_WIDTH = 50,
	FROG_HEIGHT = 50,
	FROG_ANIM_1 = 0,
	FROG_ANIM_2 = FROG_MOTION_OFFSET_X,
	LOG_Y_1 = 100,
	LOG_Y_2 = 150,
	LOG_Y_3 = 200,
	LOG_Y_4 = 250,
	WATER_ZONE_Y = 300,
	LOG_WIDTH = 100,
	LOG_HEIGHT = 50,
	
	CAR_Y_1 = 350,
	CAR_Y_2 = 400,
	CAR_Y_3 = 450,
	CAR_Y_4 = 500,
	CAR_WIDTH = 100,
	CAR_HEIGHT = 50,
	DIST_BEFORE_CAR_DISAPPEAR = 100,
	DIST_BEFORE_LOG_DISAPPEAR = 100,
	SPEED_CAR = 5,
	SPEED_FAST_CAR = 8,
	SPEED_LOG = 5,
	SPEED_FAST_LOG = 8,
	SPEED_PLAYER = 50;

var HOME_1_X = 50,
	HOME_1_Y = 50,
	HOME_2_X = 200,
	HOME_2_Y = 50,
	HOME_3_X = 350,
	HOME_3_Y = 50,
	HOME_4_X = 500,
	HOME_4_Y = 50,
	HOME_5_X = 650,
	HOME_5_Y = 50,
	HOME_WIDTH = 50,
	HOME_HEIGHT = 50,
	HOME_STATUS_OCCUPIED = "occupied",
	HOME_STATUS_EMPTY = "empty";

//Game Text
var TEXT_TIME = "Time: ",
	TEXT_TIME_X = 20,
	TEXT_TIME_Y = 20,
	TEXT_LIFE = "Life: ",
	TEXT_LIFE_X = 700,
	TEXT_LIFE_Y = 20,
	TEXT_SPACEBAR_HELP = "Click or press Spacebar to begin ...",
	TEXT_SPACEBAR_HELP_X = 240,
	TEXT_SPACEBAR_HELP_Y = 400;	